
  [[redirects]]
  from = "/gitee-img/*"
  to = "https://gitee.com/ammonium-sulphate/my-picture-bed/raw/master/:splat"  # 替换占位符
  status = 200
  force = true
  # 添加代理设置
  [redirects.proxy]
    followRedirects = true
    force404 = false